# This is a first test for travis
language: cpp
install: make get-deps
compiler: gcc
env: 
        - BUILD_SYSTEM=qmake
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq gdb qt5-qmake libqt5core5 libqt5gui5 libqt5multimedia5 libqt5opengl5-dev libqt5sql5 libqt5sql5-sqlite libqt5webkit5-dev libqt5widgets5 libqt5xml5 libqt5xmlpatterns5-dev
script: 
	- make clean
        - make
	- lemurien -test
